import Head from 'next/head'

import Layout from '@components/Layout';
import Container from '@components/Container';

import styles from '@styles/Page.module.scss'

export default function About() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
       <h1>About us</h1>
      </Container>
    </Layout>
  )
}