import withAuth from '../auth/withAuth';
import { useUser } from '../auth/useUser';

import Layout from '@components/Layout';
import Head from 'next/head';
import Container from '@components/Container';
import styles from '../styles/Page.module.scss'

const Private = () => {
  const { user, logout } = useUser();

  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container className={styles.fullHeight}>
      <div >
      <div>Private</div>
      {
        user?.email &&
        <div>
          <div>Email: {user.email}</div>
          <button onClick={() => logout()}>Logout</button>
        </div> 
      }
    </div>
      </Container>
    </Layout>
  )
}

export default withAuth(Private);


  