import Head from 'next/head'

import Layout from '@components/Layout';
import Header from '@components/Header';
import Container from '@components/Container';
import Button from '@components/Button';
import Link from 'next/link';

import styles from '@styles/Categories.module.scss'

export default function Category() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container className={styles.fullHeight}>
      <div className={styles.directory}>
            <div className={styles.wrap}>
                <div
                className={styles.item}
                style={{
                    backgroundImage: `url("https://i.pinimg.com/originals/da/05/11/da051195f24e7b285cf0cf1055abd3f4.jpg")`
                    }}>
                        <Link href="/categories/mangas">
              <a>Mangas</a>
            </Link>
                </div>
                <div
                    className={styles.item}
                    style={{ 
                    backgroundImage: `url("https://www.japananime.fr/wp-content/uploads/2022/03/luffy-kabuki.jpg")`
                    }}>
                        <Link href="/categories/figurines">
              <a>Figurines</a>
            </Link>
                </div>
            </div>
        </div>
      </Container>
    </Layout>
  )
}